### ISSUE TITLE
Css files are missing

### ISSUE THREAD

**Issue by jijith1309** [CodAffection/To-Do-List-App-in-Angular-5#1]
Hi ,

All the css files are not included in the project.Please include that too.

**Comment by CodAffection** [comment]
Fixed with inline styles array [here](https://github.com/CodAffection/To-Do-List-App-in-Angular-5/blob/875ef43f494b41f21cc276acae2a171e5999bee7/todolistapp/src/app/todo/todo.component.ts#L7)
